# Generated by Django 5.1.1 on 2024-09-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0003_alter_borrowing_book_id_alter_borrowing_user_id"),
        ("library", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="book_id",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="book_id",
            field=models.ManyToManyField(related_name="borrowings", to="library.book"),
        ),
    ]
