# Generated by Django 5.1.1 on 2024-09-14 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0004_remove_borrowing_book_id_borrowing_book_id"),
        ("library", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="book_id",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="book_id",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowings",
                to="library.book",
            ),
        ),
    ]
