# Generated by Django 5.1.1 on 2024-09-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0008_alter_borrowing_book_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="user_id",
            new_name="user",
        ),
    ]
